apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delivery-pvc
  namespace: foodgo
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-db
  namespace: foodgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-db
  template:
    metadata:
      labels:
        app: delivery-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports: [{containerPort: 5432}]
          env:
            - name: POSTGRES_DB
              value: "deliverydb"
            - name: POSTGRES_USER
              value: "delivery"
            - name: POSTGRES_PASSWORD
              value: "deliverypw"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: delivery-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-db
  namespace: foodgo
spec:
  type: ClusterIP
  selector:
    app: delivery-db
  ports:
    - port: 5432
      targetPort: 5432
